"""Export recovered circuit topology to a SPICE netlist."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from .config import AppConfig
from .detection import ComponentDetection

if TYPE_CHECKING:
    from .graph_builder import CircuitTopology

LOGGER = logging.getLogger(__name__)


@dataclass(slots=True)
class NetlistResult:
    """Text and warnings produced by SPICE export."""

    text: str
    warnings: list[str] = field(default_factory=list)


class NetlistExporter:
    """Write SPICE-compatible netlists from recovered component topology."""

    def __init__(self, config: AppConfig) -> None:
        self.config = config

    def export(self, topology: CircuitTopology, title: str = "schematic_ocr") -> NetlistResult:
        """Create netlist text from a topology object."""

        warnings = list(topology.warnings)
        lines: list[str] = [
            f"* {title}",
            "* Generated by statics_ocv schematic OCR pipeline",
        ]

        used_models: set[str] = set()
        for component in sorted(topology.components, key=_component_sort_key):
            if component.is_ground:
                continue
            line, component_warnings, models = self._component_line(component)
            warnings.extend(component_warnings)
            used_models.update(models)
            if line:
                lines.append(line)

        for model_name in sorted(used_models):
            statement = self.config.spice.model_statements.get(model_name)
            if statement:
                lines.append(statement)

        lines.append(".end")
        text = "\n".join(lines) + "\n"
        return NetlistResult(text=text, warnings=warnings)

    def write(
        self,
        topology: CircuitTopology,
        output_path: str | Path,
        title: str = "schematic_ocr",
    ) -> NetlistResult:
        """Export and write a netlist to disk."""

        result = self.export(topology, title=title)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(result.text, encoding="utf-8")
        LOGGER.info("Wrote SPICE netlist to %s", path)
        return result

    def _component_line(
        self,
        component: ComponentDetection,
    ) -> tuple[str | None, list[str], set[str]]:
        """Format one SPICE element card."""

        warnings: list[str] = []
        models: set[str] = set()
        prefix = component.spice_prefix.upper()
        nodes = list(component.terminal_nets)
        expected = self.config.terminal_count_for_prefix(prefix)

        if len(nodes) < expected:
            missing = expected - len(nodes)
            nodes.extend(f"NC_{component.element_name}_{idx + 1}" for idx in range(len(nodes), expected))
            warnings.append(
                f"{component.element_name}: netlist export filled {missing} missing node(s)."
            )

        value = component.value or self.config.spice.default_values.get(prefix, "1")

        if prefix in {"R", "C", "L"}:
            return (
                f"{component.element_name} {nodes[0]} {nodes[1]} {value}",
                warnings,
                models,
            )

        if prefix in {"V", "I"}:
            source_value = value if value.upper().startswith(("DC", "AC", "SIN", "PULSE")) else f"DC {value}"
            return (
                f"{component.element_name} {nodes[0]} {nodes[1]} {source_value}",
                warnings,
                models,
            )

        if prefix == "D":
            model = value or "DDEFAULT"
            models.add(model)
            return (
                f"{component.element_name} {nodes[0]} {nodes[1]} {model}",
                warnings,
                models,
            )

        if prefix == "Q":
            model = value or "QDEFAULT"
            models.add(model)
            return (
                f"{component.element_name} {nodes[0]} {nodes[1]} {nodes[2]} {model}",
                warnings,
                models,
            )

        if prefix == "M":
            model = value or "MDEFAULT"
            models.add(model)
            drain, gate, source = nodes[:3]
            body = source
            return (
                f"{component.element_name} {drain} {gate} {source} {body} {model}",
                warnings,
                models,
            )

        if prefix == "S":
            model = value or "SWDEFAULT"
            models.add(model)
            control_pos = nodes[2]
            control_neg = nodes[3]
            return (
                f"{component.element_name} {nodes[0]} {nodes[1]} {control_pos} {control_neg} {model}",
                warnings,
                models,
            )

        if prefix == "X":
            subckt = value or self.config.spice.default_values.get("X", "SUBCKT")
            return (
                f"{component.element_name} {' '.join(nodes)} {subckt}",
                warnings,
                models,
            )

        warnings.append(
            f"{component.element_name}: unsupported SPICE prefix {prefix}; skipped."
        )
        return None, warnings, models


def _component_sort_key(component: ComponentDetection) -> tuple[str, str]:
    prefix = "Z" if component.is_ground else component.spice_prefix.upper()
    return prefix, component.element_name
